brand_research_task:
  description: >
    Gather information on brand history, values, competitors, and target demographics.
  expected_output: >
    A comprehensive report with key findings and recommendations.
  agent: brand_research_agent

strategy_task:
  description: >
    Formulate a marketing strategy based on the research insights and campaign goals.
  expected_output: >
    A detailed marketing plan with clear objectives, target audience, key messages,
  agent: strategy_agent
